site:
  lang: "en"
  index:
    title: "Certificates for WordCamp São Paulo 2016"
    message: "Instructions here"
    emailPlaceholder: "myemail@email.com"
    submit: "Generate my certificate"
routes:
  certificate: certificate
csv: csv/sample.csv